# Generated by Django 2.0 on 2017-12-24 02:15

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='In progress', max_length=100, no_check_for_status=True),
        ),
    ]
